jwt_secret: 34t43f4f44234fd43f
server:
  port: 8080
spring:
  security:
    user:
      name: zip3
      password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/first_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true